export {absolute} from './absolute'
export {factorial} from './factorial'
export {factors} from './factors'
export {mean} from './mean'
// import './power'
// import './prime'
// import './sqrt'
// import './remainder'
// import './str_titlecase'
// import './arr_flatten'

