export {absolute} from './absolute'
export {mean} from './mean'
export {sqrt} from './sqrt'
export {factorial} from './factorial'
export {factors} from './factors'
export {square, cube, power} from './exponent'
export {isPrime} from './prime'
export {remainder} from './remainder'
export {titleCase} from './str_titlecase'
export {arrayFlatten} from './arr_flatten'
export {arrayUnique} from './arr_unique'

